version: '3.8'

services:
  finance_dashboard_server:
    image: 'nginx:stable-alpine'
    build:
      context: .
      dockerfile: dockerfiles/nginx.dockerfile
    container_name: finance_dashboard_server
    ports:
      - '8003:80'
    volumes:
      - ../:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - laravel_api

  php_finance_dashboard:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    container_name: finance_dashboard_laravel
    volumes:
      - ../:/var/www/html:delegated
    networks:
      - laravel_api

  composer_finance_dashboard: 
    build:
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ../:/var/www/html
    networks:
      - laravel_api

  artisan_finance_dashboard:
    build:
      context: .
      dockerfile: dockerfiles/php.dockerfile
    volumes:
      - ../:/var/www/html
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      - laravel_api

  npm_finance_dashboard:
    image: node:14
    working_dir: /var/www/html
    command: ['npm', 'install']
    volumes:
      - ../:/var/www/html
    networks:
      - laravel_api

networks:
  laravel_api:
    external: true
    driver: bridge
